default_platform(:android)

platform :android do
  desc "Firebase App Distribution"
  lane :qa do
    begin
      gradle(
          task: "clean assembleRelease"
      )

      firebase_app_distribution(
          app: ENV['FIREBASE_APP_ID'],
          groups: "bongbaek_qa",
          release_notes_file: "fastlane/release-notes.txt"
      )

      discord_notifier(
          webhook_url: ENV['DISCORD_DEPLOY_WEBHOOK_URL'],
          title: "✅ 새로운 릴리즈 빌드가 배포되었습니다! Firebase에서 확인해주세요. 🚀",
          description: "✅ 봉투백서가 배포되었습니다!"
      )

    rescue => exception
      discord_notifier(
          webhook_url: ENV['DISCORD_DEPLOY_WEBHOOK_URL'],
          title: "❌ QA 빌드 배포에 실패했습니다. 로그를 확인해주세요.",
          description: "에러: #{exception}"
      )
      raise exception
    end
  end

  desc "Google Play Store Upload"
    lane :release do |options|
      begin
        target_track = options[:track] || 'beta'

        gradle(
            task: "bundleRelease"
        )

        upload_to_play_store(
            track: target_track,
            aab: lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH],
            release_status: 'completed'
        )

        discord_notifier(
            webhook_url: ENV['DISCORD_DEPLOY_WEBHOOK_URL'],
            title: "✅ 새로운 릴리즈 빌드가 Play 스토어에 배포되었습니다! 🚀",
            description: "✅ 봉투백서가 '#{target_track}' 트랙에 성공적으로 업로드되었습니다."
        )

      rescue => exception
        discord_notifier(
            webhook_url: ENV['DISCORD_DEPLOY_WEBHOOK_URL'],
            title: "❌ 릴리즈 빌드 배포에 실패했습니다. 로그를 확인해주세요.",
            description: "에러: #{exception}"
        )
      raise exception
    end
  end
end
