name: BongBaek Develop CI

# Every new pull request to develop branch must fire CI check
on:
  pull_request:
    branches: [ "develop" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Create local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: |
          if [ -n "$LOCAL_PROPERTIES" ]; then
            echo "${LOCAL_PROPERTIES}" > local.properties
            echo "sdk.dir=$ANDROID_SDK_ROOT" >> local.properties
          else
            echo "LOCAL_PROPERTIES not found."
          fi

      - name: Create google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          if [ -n "$GOOGLE_SERVICES_JSON" ]; then
            echo "${GOOGLE_SERVICES_JSON}" > ./app/src/debug/google-services.json
          else
            echo "GOOGLE_SERVICES_JSON not found."
          fi

      - name: Restore debug keystore
        env:
          DEBUG_KEYSTORE_BASE64: ${{ secrets.DEBUG_KEYSTORE_BASE64 }}
        run: |
          if [ -n "$DEBUG_KEYSTORE_BASE64" ]; then
            mkdir -p ./keystore
            echo "$DEBUG_KEYSTORE_BASE64" | base64 --decode > ./keystore/bongbaek-debug-key.jks
          else
            echo "DEBUG_KEYSTORE_BASE64 not found."
          fi

      - name: Build with Gradle
        run: ./gradlew :app:assembleDebug

      - name: Run unit test
        run: ./gradlew testDebugUnitTest
